apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: nginx
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: 'HTTP'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '10'
    alb.ingress.kubernetes.io/success-codes: "200-499"
    alb.ingress.kubernetes.io/target-type: 'ip'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/subnets: subnet-09ae78da6e6f8f061, subnet-07ff33341602e2b83
spec:
  ingressClassName: alb
  rules:
  - host: sinovuyo.975050059616.realhandsonlabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: nginx-service
           port:
            number: 80
      - path: /argocd
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
             number: 80
